package com.example.demo.model;

public enum Status {
    SUCCESS, FAIL, SIGNED_IN, LOGGED_OUT, ALREADY_EXISTS, ALREADY_EXISTS_AND_LOGGED_IN, USER_CREATED, USER_CREATED_AND_LOGGED_IN, NOT_SUCH_USER_EXISTS,
}
